export const SPRINT_FETCH_REQUEST = 'SPRINT_FETCH_REQUEST'
export const SPRINT_FETCH_FAILURE = 'SPRINT_FETCH_FAILURE'

export const FETCH_SPRINT_LIST_SUCCESS = 'FETCH_SPRINT_LIST_SUCCESS'
export const UPDATE_SPRINT_FOR_TASK_SUCCESS = 'UPDATE_SPRINT_FOR_TASK_SUCCESS'
export const DELETE_SPRINT_SUCCESS = 'DELETE_SPRINT_SUCCESS'
export const CREATE_SPRINT_SUCCESS = 'CREATE_SPRINT_SUCCESS'
export const UPDATE_SPRINT_SUCCESS = 'UPDATE_SPRINT_SUCCESS'
export const START_SPRINT_SUCCESS = 'START_SPRINT_SUCCESS'