export const BACKLOG_FETCH_REQUEST = 'BACKLOG_FETCH_REQUEST'
export const BACKLOG_FETCH_FAILURE = 'BACKLOG_FETCH_REQUEST'

export const TASK_LIST_SUCCESS = 'TASK_LIST_SUCCESS'
export const UPDATE_TASK_FOR_SPRINT_SUCCESS = 'UPDATE_TASK_FOR_SPRINT_SUCCESS'